### ISSUE TITLE
fmt::Display impl of BlockUtilsError have a infinite recursive loop

### ISSUE THREAD

**Issue by lumasepa** [cholcombe973/block-utils#17]
First of all, thanks for this lib, has been very useful.

The problem is that `fmt::Display` impl of BlockUtilsError calls `self.to_string()` whom implementation is in `ToString` trait, who depend on `Display`. So what happens, Display::fmt()  calls ToString::to_string() who calls Display::fmt() and so on. This is only triggered if you try to format the error.

**Comment by cholcombe973** [comment]
Well that's a terrible bug. Thanks for submitting a fix!
